### ISSUE TITLE
Question about gluetun VPN

### ISSUE THREAD

**Issue by gandazgul** [npawelek/k8s-gitops#316]
I'm having issues with the VPN I want the sidecar to stop when the VPN stop. I copied your livelinessProbe (thank you) but I get an error `Liveness probe failed: PING 1.1.1.1 (1.1.1.1): 8 data bytes ping: permission denied (are you root?)`

Kubernetes 1.20 on Fedora 33 bare metal

Have you seen this before?

thank you

**Comment by npawelek** [comment]
@gandazgul I run this sidecar on specific containers which have root access.
